In [ ]:
!pip uninstall tensorflow==2.9.2
!pip install tensorflow==2.8.2

Found existing installation: tensorflow 2.9.2
Uninstalling tensorflow-2.9.2:
  Would remove:
    /usr/local/bin/estimator_ckpt_converter
    /usr/local/bin/import_pb_to_tensorboard
    /usr/local/bin/saved_model_cli
    /usr/local/bin/tensorboard
    /usr/local/bin/tf_upgrade_v2
    /usr/local/bin/tflite_convert
    /usr/local/bin/toco
    /usr/local/bin/toco_from_protos
    /usr/local/lib/python3.7/dist-packages/tensorflow-2.9.2.dist-info/*
    /usr/local/lib/python3.7/dist-packages/tensorflow/*
Proceed (y/n)? y
  Successfully uninstalled tensorflow-2.9.2
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 437.8 MB 34 kB/s 
     |████████████████████████████████| 5.8 MB 4.3 MB/s 
     |████████████████████████████████| 462 kB 76.9 MB/s 
     |████████████████████████████████| 1.4 MB 48.4 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.9.0
  

In [ ]:
import tensorflow as tf
print(tf.__version__)

'2.8.2'

In [ ]:
import pandas as pd
import os
import string
import numpy as np
from collections import Counter

In [ ]:
dataset_text = 'drive/MyDrive/iNeuron/NLP/Reuters/reviews.txt'
dataset_label = 'drive/MyDrive/iNeuron/NLP/Reuters/labels.txt'
stopwords_path = 'drive/MyDrive/iNeuron/NLP/stopwords.txt'


with open(dataset_text, 'r') as f:
  texts = f.read()
with open(dataset_label, 'r') as f:
  labels = f.read().split('\n')
with open(stopwords_path, 'r') as f:
  stopwords  = f.read().split('\n')

print(texts[:51])
print(labels)
print(stopwords)

bromwell high is a cartoon comedy . it ran at the s
['positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive',

In [ ]:
sentences = []
for each_sentence in texts.split('\n'):
  sentences.append(''.join([each_char for each_char in each_sentence if each_char not in string.punctuation]))

In [ ]:
import spacy
import re

In [ ]:
nlp = spacy.load("en_core_web_sm")
pattern = "@\S+|https?:\S+|http?:\S|[^A-Za-z0-9]+"
nlp('being bromwell high is a cartoon comedy . it ran at the s')

being bromwell high is a cartoon comedy . it ran at the s

In [9]:
text_data = []
count = 0
for line in sentences:
  count+=1
  if count%100 == 0:
    print(count)
  clean_text = []

  line = nlp(line)
  for token in line:
    clean = re.sub(pattern, '', str(token.lemma_).lower())

    if clean not in stopwords:
      clean_text.append(clean)

  text_data.append(' '.join(clean_text).replace('  ', ' '))

100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900
13000
13100
13200
13300
13400
13500
13600
13700
13800
13900
14000
14100
14200
14300
14400
14500
14600
14700
14800
14900
15000
15100
15200
15300
15400
15500
15600
15700
15800
15900
16000
16100
16200
16300
16400
16500
16600
16700
16800
16900
17000
17100
17200
17300
17400
17500
17600
17700
17800
17900
18000
18100
18200
18300
18400
1850

In [10]:
print(len(text_data))
print(len(labels))

25001
25001


In [11]:
instant = np.array([1 if single_label=="positive" else 0 for single_label in labels])
instant[100:120]

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [12]:
text_data = np.array(text_data)
instant = np.array(instant)

In [13]:
text_data[0]

'bromwell high cartoon comedy run time program school life  teacher  year teaching profession lead believe bromwell high satire much close reality teacher scramble survive financially insightful student see right pathetic teacher pomp pettiness whole situation remind school know student see episode student repeatedly try burn school immediately recall  high classic line inspector m sack one teacher student welcome bromwell high expect many adult age think bromwell high far fetched pity isn '

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import naive_bayes
import pickle

In [15]:
df = pd.DataFrame(text_data, columns=['text'])
df['labels'] = instant
df

text  labels
0      bromwell high cartoon comedy run time program ...       1
1      story man unnatural feeling pig start opening ...       0
2      homelessness houselessness george carlin state...       1
3      airport start brand new luxury plane load valu...       0
4      brilliant act lesley ann warren good dramatic ...       1
...                                                  ...     ...
24996  christmas together actually come time  ve rais...       1
24997  film pick pound turn rather good rd century fi...       0
24998  work class romantic drama director martin ritt...       1
24999  one dumb film  ve ever see rip nearly ever typ...       0
25000                                                          0

[25001 rows x 2 columns]

In [16]:
# Randomized Here
df.iloc[:,:] = df.sample(frac=1, random_state=63, ignore_index=True)
df


text  labels
0       bye bye birdie isn one good musical time  gre...       1
1      far provide caffeine kick d expect film share ...       0
2       domino principle  without question one bad th...       0
3      let start say watch episode first time dvd o c...       1
4       indian burial ground three word appear anywhe...       0
...                                                  ...     ...
24996  stargate sg spin sort movie stargate glad deci...       1
24997  neither total disaster uk critic claim misunde...       1
24998  nintendo er could  believe movie actually bad ...       0
24999   ve see small likable comical film sure feel w...       1
25000  movie incredible great character specially old...       1

[25001 rows x 2 columns]

In [17]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(df, test_size = 0.25)
print(train.shape, test.shape)

(18750, 2) (6251, 2)


In [18]:
print(train.shape)
train[:1]

(18750, 2)


text  labels
11634  movie great first time see call lose translati...       0

Go to your Model

In [ ]:
TfidfVect = TfidfVectorizer()
TfidfVect.fit(train['text'])

x_vector = TfidfVect.transform(train['text'])
print(x_vector.shape)

(18750, 53973)


In [ ]:
print(x_vector[0].toarray())

[[0. 0. 0. ... 0. 0. 0.]]


In [ ]:
with open('drive/MyDrive/iNeuron/NLP/Reuters/embed.pickle', 'wb') as f:
  pickle.dump(TfidfVect, f)

In [ ]:
x_vector.shape

(18750, 54006)

In [ ]:
model = naive_bayes.MultinomialNB()
model.fit(x_vector, train['labels'])

MultinomialNB()

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
train_pred = model.predict(x_vector)
confusion_matrix(train['labels'], train_pred)

array([[8760,  648],
       [ 998, 8344]])

In [ ]:
with open('drive/MyDrive/iNeuron/NLP/Reuters/modelPrediction.sav', 'wb') as f:
  pickle.dump(model, f)

In [ ]:
with open('drive/MyDrive/iNeuron/NLP/Reuters/embed.pickle', 'wb') as f:
  pickle.dump(TfidfVect, f)

Testing

In [ ]:
with open('drive/MyDrive/iNeuron/NLP/Reuters/embed.pickle', 'rb') as f:
  vectorizer = pickle.load(f)

with open('drive/MyDrive/iNeuron/NLP/Reuters/modelPrediction.sav', 'rb') as f:
  test_model = pickle.load(f)

In [ ]:
print(test.columns)
test.shape

Index(['text', 'labels'], dtype='object')


(6251, 2)

In [ ]:
pred_vector = vectorizer.transform(test['text'])
print(pred_vector.shape)

(6251, 54006)


In [ ]:
test_pred = model.predict(pred_vector)
confusion_matrix(test['labels'], test_pred)

array([[2730,  363],
       [ 472, 2686]])

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(test['labels'], test_pred))

              precision    recall  f1-score   support

           0       0.85      0.88      0.87      3093
           1       0.88      0.85      0.87      3158

    accuracy                           0.87      6251
   macro avg       0.87      0.87      0.87      6251
weighted avg       0.87      0.87      0.87      6251



Embedding

In [19]:
import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import confusion_matrix

In [20]:
token = Tokenizer()
token.fit_on_texts(train['text'])
vocab_size = len(token.word_index) + 1
vocab_size

54238

In [21]:
encoded_docs = token.texts_to_sequences(train['text'])

In [22]:

review_lens = [len(x) for x in encoded_docs]
len_frame = pd.Series(review_lens)
data_desc = len_frame.describe()
print(data_desc)
print(data_desc['75%'])
print()

count    18750.000000
mean       124.703360
std         94.516838
min          4.000000
25%         66.000000
50%         92.000000
75%        151.000000
max        952.000000
dtype: float64
151.0



In [23]:
aa = len_frame.quantile([.9])
max_length = int(aa[0.9])
max_length

247

In [24]:
# max_length: Number of sequence Tokens accepted 
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs.shape)

(18750, 247)


In [25]:
embeddings_index = {}
with open('drive/MyDrive/Dataset/glove.6B.50d.txt', 'r') as f:
  for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
print("loaded ", len(embeddings_index))

loaded  400000


In [26]:
embedding_matrix = np.zeros((vocab_size, 50))
for word, i in token.word_index.items():
  tmp_vector = embeddings_index.get(word)
  if tmp_vector is not None:
    embedding_matrix[i] = tmp_vector

In [27]:
print(embedding_matrix.shape)

(54238, 50)


In [ ]:
model = Sequential()
embed = Embedding(vocab_size, 50, weights=[embedding_matrix], input_length=max_length, trainable=False)
model.add(embed)
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 247, 50)           2711750   
                                                                 
 flatten_2 (Flatten)         (None, 12350)             0         
                                                                 
 dense_2 (Dense)             (None, 1)                 12351     
                                                                 
Total params: 2,724,101
Trainable params: 12,351
Non-trainable params: 2,711,750
_________________________________________________________________
None


In [ ]:
early_stopping = EarlyStopping(patience=5, monitor="accuracy")

In [ ]:
model.fit(padded_docs, train['labels'], epochs=25, verbose=1, callbacks=[early_stopping])

Epoch 1/25
586/586 [==============================] - 2s 3ms/step - loss: 0.6118 - accuracy: 0.6830
Epoch 2/25
586/586 [==============================] - 2s 3ms/step - loss: 0.4688 - accuracy: 0.7821
Epoch 3/25
586/586 [==============================] - 2s 3ms/step - loss: 0.4216 - accuracy: 0.8069
Epoch 4/25
586/586 [==============================] - 2s 3ms/step - loss: 0.3874 - accuracy: 0.8243
Epoch 5/25
586/586 [==============================] - 2s 3ms/step - loss: 0.3666 - accuracy: 0.8369
Epoch 6/25
586/586 [==============================] - 2s 3ms/step - loss: 0.3502 - accuracy: 0.8453
Epoch 7/25
586/586 [==============================] - 2s 3ms/step - loss: 0.3373 - accuracy: 0.8505
Epoch 8/25
586/586 [==============================] - 2s 3ms/step - loss: 0.3275 - accuracy: 0.8570
Epoch 9/25
586/586 [==============================] - 2s 3ms/step - loss: 0.3180 - accuracy: 0.8634
Epoch 10/25
586/586 [==============================] - 2s 3ms/step - loss: 0.3080 - accuracy: 0.8653

In [ ]:
loss, accuracy = model.evaluate(padded_docs, train['labels'], verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 92.261332


Testing the Embedding Model

In [28]:
test_docs = token.texts_to_sequences(test['text'])
test_docs = pad_sequences(test_docs, maxlen=max_length, padding='post')
print(test_docs.shape)

(6251, 247)


In [ ]:
loss, accuracy = model.evaluate(test_docs, test['labels'], verbose=1)
print('Accuracy: %f' % (accuracy*100))

196/196 [==============================] - 1s 3ms/step - loss: 1.2918 - accuracy: 0.6799
Accuracy: 67.989123


In [ ]:
test_pred = model.predict(test_docs)

predictions = (model.predict(test_docs) > 0.5).astype("int32")
predictions

196/196 [==============================] - 1s 2ms/step


array([[0],
       [0],
       [0],
       ...,
       [1],
       [0],
       [0]], dtype=int32)

In [ ]:
#predictions = np.argmax(model.predict(test_docs),axis=1)
#predictions

196/196 [==============================] - 0s 2ms/step


array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
confusion_matrix(test['labels'], predictions)

array([[2177,  950],
       [1051, 2073]])

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(test['labels'], predictions))

              precision    recall  f1-score   support

           0       0.67      0.70      0.69      3127
           1       0.69      0.66      0.67      3124

    accuracy                           0.68      6251
   macro avg       0.68      0.68      0.68      6251
weighted avg       0.68      0.68      0.68      6251



Simple RNN Using GloVe 50D

In [30]:
from tensorflow.keras.layers import SimpleRNN, Activation, LSTM, Bidirectional, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

In [ ]:
def vanilla_rnn():
    model = Sequential()
    embed = Embedding(vocab_size, 50, weights=[embedding_matrix], input_length=max_length, trainable=False)
    model.add(embed)
    model.add(SimpleRNN(50, input_shape = (49,1), return_sequences = False))
    model.add(Dense(1))
    model.add(Activation('sigmoid'))
    
    adam = Adam(learning_rate=0.001)
    model.compile(loss = 'binary_crossentropy', optimizer = adam, metrics = ['accuracy'])
    
    return model

In [ ]:
vanilla_model = vanilla_rnn()
vanilla_model.summary()

Model: "sequential_18"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_18 (Embedding)    (None, 247, 50)           2704350   
                                                                 
 simple_rnn_26 (SimpleRNN)   (None, 50)                5050      
                                                                 
 dense_17 (Dense)            (None, 1)                 51        
                                                                 
 activation_13 (Activation)  (None, 1)                 0         
                                                                 
Total params: 2,709,451
Trainable params: 5,101
Non-trainable params: 2,704,350
_________________________________________________________________


In [ ]:
early_stopping = EarlyStopping(patience=5, monitor="accuracy")
simple_model = vanilla_rnn()
simple_model.fit(padded_docs, train['labels'], epochs = 50, verbose = 1, callbacks=[early_stopping])

Epoch 1/50
586/586 [==============================] - 35s 57ms/step - loss: 0.6966 - accuracy: 0.5127
Epoch 2/50
586/586 [==============================] - 34s 57ms/step - loss: 0.6906 - accuracy: 0.5058
Epoch 3/50
586/586 [==============================] - 34s 59ms/step - loss: 0.6898 - accuracy: 0.5110
Epoch 4/50
586/586 [==============================] - 33s 57ms/step - loss: 0.6898 - accuracy: 0.5124
Epoch 5/50
586/586 [==============================] - 33s 57ms/step - loss: 0.6867 - accuracy: 0.5182
Epoch 6/50
586/586 [==============================] - 33s 56ms/step - loss: 0.6842 - accuracy: 0.5187
Epoch 7/50
586/586 [==============================] - 32s 55ms/step - loss: 0.6834 - accuracy: 0.5181
Epoch 8/50
586/586 [==============================] - 33s 57ms/step - loss: 0.6820 - accuracy: 0.5233
Epoch 9/50
586/586 [==============================] - 33s 57ms/step - loss: 0.6794 - accuracy: 0.5226
Epoch 10/50
586/586 [==============================] - 33s 56ms/step - loss: 0.679

In [ ]:
loss, accuracy = simple_model.evaluate(padded_docs, train['labels'], verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 52.288002


In [ ]:
loss, accuracy = simple_model.evaluate(test_docs, test['labels'], verbose=1)
print('Accuracy: %f' % (accuracy*100))

196/196 [==============================] - 4s 18ms/step - loss: 0.6935 - accuracy: 0.5102
Accuracy: 51.015836


In [ ]:
predictions = (simple_model.predict(test_docs) > 0.5).astype("int32")
predictions

array([[1],
       [1],
       [1],
       ...,
       [0],
       [1],
       [1]], dtype=int32)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(test['labels'], predictions))

              precision    recall  f1-score   support

           0       0.56      0.07      0.12      3104
           1       0.51      0.95      0.66      3147

    accuracy                           0.51      6251
   macro avg       0.53      0.51      0.39      6251
weighted avg       0.53      0.51      0.39      6251



Stacked Rnn using gloVe 50D

In [44]:
def stacked_rnn():
    model = Sequential()
    embed = Embedding(vocab_size, 50, weights=[embedding_matrix], input_length=max_length, trainable=False)
    model.add(embed)
    model.add(SimpleRNN(50, input_shape = (49,1), return_sequences = True))
    model.add(SimpleRNN(50, return_sequences = False))
    model.add(Dense(1, activation = 'sigmoid'))
    
    adam = Adam(learning_rate=0.001)
    model.compile(loss = 'binary_crossentropy', optimizer = adam, metrics = ['accuracy'])
    
    return model

In [45]:
stacked_model = stacked_rnn()
stacked_model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_7 (Embedding)     (None, 247, 50)           2711900   
                                                                 
 simple_rnn (SimpleRNN)      (None, 247, 50)           5050      
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 50)                5050      
                                                                 
 dense_5 (Dense)             (None, 1)                 51        
                                                                 
Total params: 2,722,051
Trainable params: 10,151
Non-trainable params: 2,711,900
_________________________________________________________________


In [46]:
early_stopping = EarlyStopping(patience=5, monitor="accuracy")
stacked_model.fit(padded_docs, train['labels'], epochs = 50, verbose = 1, callbacks=[early_stopping])

Epoch 1/50
586/586 [==============================] - 69s 111ms/step - loss: 0.6965 - accuracy: 0.5076
Epoch 2/50
586/586 [==============================] - 64s 110ms/step - loss: 0.6932 - accuracy: 0.5071
Epoch 3/50
548/586 [===========================>..] - ETA: 4s - loss: 0.6857 - accuracy: 0.5351

KeyboardInterrupt: ignored

In [ ]:
loss, accuracy = stacked_model.evaluate(padded_docs, train['labels'], verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 57.344002


In [ ]:
predictions = (stacked_model.predict(test_docs) > 0.5).astype("int32")
from sklearn.metrics import classification_report
print(classification_report(test['labels'], predictions))

              precision    recall  f1-score   support

           0       0.55      0.68      0.61      3104
           1       0.59      0.46      0.51      3147

    accuracy                           0.57      6251
   macro avg       0.57      0.57      0.56      6251
weighted avg       0.57      0.57      0.56      6251



In [ ]:
Counter(list(train['labels']))

Counter({0: 9397, 1: 9353})

LSTM

In [31]:
lstm_model = Sequential()
lstm_model.add(Embedding(vocab_size, 50, weights=[embedding_matrix], input_length=max_length, trainable=False))
lstm_model.add(LSTM(128, return_sequences=True))
lstm_model.add(LSTM(64, return_sequences=True))
lstm_model.add(LSTM(32))
lstm_model.add(Dropout(0.2))
lstm_model.add(Dense(1, activation='sigmoid'))

lstm_model.compile('adam', 'binary_crossentropy', metrics = ['accuracy'])


lstm_model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 247, 50)           2711900   
                                                                 
 lstm (LSTM)                 (None, 247, 128)          91648     
                                                                 
 lstm_1 (LSTM)               (None, 247, 64)           49408     
                                                                 
 lstm_2 (LSTM)               (None, 32)                12416     
                                                                 
 dropout (Dropout)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 2,865,405
Trainable params: 153,505
Non-

In [32]:
early_stopping = EarlyStopping(patience=5, monitor = 'accuracy')
lstm_model.fit(padded_docs, train['labels'], epochs = 50, verbose = 1, callbacks=[early_stopping])  

Epoch 1/50
586/586 [==============================] - 278s 464ms/step - loss: 0.6842 - accuracy: 0.5353
Epoch 2/50
586/586 [==============================] - 267s 455ms/step - loss: 0.6668 - accuracy: 0.6187
Epoch 3/50
586/586 [==============================] - 268s 457ms/step - loss: 0.6836 - accuracy: 0.5231
Epoch 4/50
586/586 [==============================] - 269s 460ms/step - loss: 0.6936 - accuracy: 0.4959
Epoch 5/50
586/586 [==============================] - 269s 459ms/step - loss: 0.6935 - accuracy: 0.4989
Epoch 6/50
586/586 [==============================] - 273s 466ms/step - loss: 0.6934 - accuracy: 0.5031
Epoch 7/50
586/586 [==============================] - 293s 500ms/step - loss: 0.6934 - accuracy: 0.5008


In [33]:
predictions = (lstm_model.predict(test_docs) > 0.5).astype("int32")
from sklearn.metrics import classification_report
print(classification_report(test['labels'], predictions))

              precision    recall  f1-score   support

           0       0.50      1.00      0.67      3135
           1       0.00      0.00      0.00      3116

    accuracy                           0.50      6251
   macro avg       0.25      0.50      0.33      6251
weighted avg       0.25      0.50      0.34      6251



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Bidirectional LSTM

In [41]:
bi_lstm = Sequential()
bi_lstm.add(Embedding(vocab_size, 50, weights=[embedding_matrix], input_length = max_length, trainable = False))
bi_lstm.add(Bidirectional(LSTM(64, dropout=0.2, recurrent_dropout=0.2, return_sequences=True)))
bi_lstm.add(Bidirectional(LSTM(64, dropout=0.1, recurrent_dropout=0.1)))
bi_lstm.add(Dense(1, activation='sigmoid'))

bi_lstm.compile('adam', 'binary_crossentropy', metrics = ['accuracy'])

bi_lstm.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_6 (Embedding)     (None, 247, 50)           2711900   
                                                                 
 bidirectional_5 (Bidirectio  (None, 247, 128)         58880     
 nal)                                                            
                                                                 
 bidirectional_6 (Bidirectio  (None, 128)              98816     
 nal)                                                            
                                                                 
 dense_4 (Dense)             (None, 1)                 129       
                                                                 
Total params: 2,869,725
Trainable params: 157,825
Non-trainable params: 2,711,900
_________________________________________________________________


In [42]:
early_stopping = EarlyStopping(patience=5, monitor = 'accuracy')
bi_lstm.fit(padded_docs, train['labels'], epochs = 50, verbose = 1, callbacks=[early_stopping]) 

Epoch 1/50
586/586 [==============================] - 559s 935ms/step - loss: 0.5687 - accuracy: 0.7088
Epoch 2/50
586/586 [==============================] - 534s 911ms/step - loss: 0.5384 - accuracy: 0.7360
Epoch 3/50
586/586 [==============================] - 548s 935ms/step - loss: 0.5072 - accuracy: 0.7605
Epoch 4/50
586/586 [==============================] - 548s 935ms/step - loss: 0.4572 - accuracy: 0.7912
Epoch 5/50
586/586 [==============================] - 554s 946ms/step - loss: 0.4099 - accuracy: 0.8165
Epoch 6/50
586/586 [==============================] - 550s 938ms/step - loss: 0.3898 - accuracy: 0.8269
Epoch 7/50
586/586 [==============================] - 552s 942ms/step - loss: 0.3771 - accuracy: 0.8329
Epoch 8/50
586/586 [==============================] - 643s 1s/step - loss: 0.3630 - accuracy: 0.8430
Epoch 9/50
586/586 [==============================] - 556s 949ms/step - loss: 0.3515 - accuracy: 0.8461
Epoch 10/50
586/586 [==============================] - 565s 965ms/s

KeyboardInterrupt: ignored

In [43]:
predictions = (bi_lstm.predict(test_docs) > 0.5).astype("int32")
from sklearn.metrics import classification_report
print(classification_report(test['labels'], predictions))

              precision    recall  f1-score   support

           0       0.87      0.85      0.86      3135
           1       0.85      0.87      0.86      3116

    accuracy                           0.86      6251
   macro avg       0.86      0.86      0.86      6251
weighted avg       0.86      0.86      0.86      6251



GRU

KerasClassifier Wrapper

In [ ]:
early_stopping = EarlyStopping(patience=5, monitor="accuracy")
vanilla_model = KerasClassifier(build_fn = vanilla_rnn, epochs = 200, batch_size = 50, verbose = 1, callbacks=[early_stopping])
vanilla_model.fit(padded_docs, train['labels'])

In [ ]:
loss, accuracy = vanilla_model.evaluate(padded_docs, train['labels'], verbose=1)
print('Accuracy: %f' % (accuracy*100))

AttributeError: ignored