Q1. Write a function so that the columns of the output matrix are powers of the input
vector.

In [1]:
import numpy as np

In [2]:
input_vec = [1, 2, 3, 4, 5]
input_copy = input_vec

def list_power(list_a, num):
    return [x**num for x in list_a]
for i in range(2, len(input_vec)+1):
    input_vec = np.vstack((input_vec, list_power(input_copy, i)))
print(input_vec)

[[   1    2    3    4    5]
 [   1    4    9   16   25]
 [   1    8   27   64  125]
 [   1   16   81  256  625]
 [   1   32  243 1024 3125]]


Q2. Write a function so that the columns of the output matrix are powers of the input
vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [4]:
x = np.array([1, 2, 3, 4, 5])
N = 5
mat = np.column_stack([x ** (N-i-1) for i in range(N)])
mat

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [20]:
full_array = np.array([3,5,7,2,8,10,11,65,72,81,99,100,150])
window_size = 3
all_round = full_array.shape[0] - window_size + 1

print('Moving Array Average')
for i in range(all_round):
    sum_a = 0
    for j in range(window_size):
        sum_a += full_array[i + j]
    #print(full_array[i]+full_array[i+1]+full_array[i+2])
    print(sum_a / window_size)

Moving Array Average
5.0
4.666666666666667
5.666666666666667
6.666666666666667
9.666666666666666
28.666666666666668
49.333333333333336
72.66666666666667
84.0
93.33333333333333
116.33333333333333
